pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git 'https://github.com/cnsidze/java-project.git'
            }
        }
        
        stage('Build') {
            steps {
                // Build your Java project (replace with your build command)
                sh 'mvn clean package'
            }
        }
        
        stage('Test') {
            steps {
                // Run your tests (replace with your test command)
                sh 'mvn test'
            }
        }
        
        stage('Artifact') {
            steps {
                // Archive the artifact (replace with your artifact archiving command)
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
    
    // Triggers the pipeline on each commit
    triggers {
        pollSCM('* * * * *')
    }
}
